runtime: python312
entrypoint: gunicorn -b :$PORT main:server
# entrypoint: gunicorn -b 0.0.0.0:8080 main:server

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 10

